### ISSUE TITLE
[Light theme] Can't view bold text with bold fonts disabled in VTE terminal.

### ISSUE THREAD

**Issue by rugglcon** [dylanaraps/pywal#175]
As a precursor, I love the new light theme feature, I never thought I would be a fan of light themes but here we are.

Anyway, when using the light theme it's extremely hard to view the man pages because the bolded text is the same color as the background. I've attached a screenshot so you can see what I mean. I'm on elementaryOS and using pantheon terminal, with the most recent version of pywal.

![light](https://user-images.githubusercontent.com/14317362/35770625-626aa7dc-08e4-11e8-9e77-cf58477ee372.png)

**Comment by dylanaraps** [comment]
I can reproduce this with bold text disabled.

**Comment by dylanaraps** [comment]
This is a much bigger issue, this affects all bold text when bold fonts are disabled.

**Comment by dylanaraps** [comment]
The issue seems to only affect VTE terminals and to me this looks like a bug in VTE. The sequence that changes the foreground color doesn't affect the bold foreground color.

In other terminals this isn't the case. The sequence covers both bold and non-bold text. I'm going to open a bug report to see what the VTE developers think of the issue.

**Comment by dylanaraps** [comment]
Bug report filed: https://bugzilla.gnome.org/show_bug.cgi?id=793152

**Comment by rugglcon** [comment]
Thanks for submitting the bug to the VTE developers and recognizing it's a deeper issue, I also got the correct colors in urxvt.

**Comment by dylanaraps** [comment]
This has been fixed in VTE. https://github.com/GNOME/vte/commit/e9989360bb3b020c4507562af9385ca7584f0d97

**Comment by aleprovencio** [comment]
Hello, unfortunately I still face this issue with Arch on:
python-pywal 3.1.0-2
vte-common 0.54.0+9+gdace9988-1
termite 13-3

**Comment by aleprovencio** [comment]
FYI, it's been working for me without workarounds. Can't point which commit, but thanks for that.
