### ISSUE TITLE
Impossible to launch

### ISSUE THREAD

**Issue by Y0lan** [dylanaraps/pywal#63]
When installing using 
`sudo pip install pywal`

or 

`git clone ... 
cd pywal
pip install pywal`

it install correctly but whenever I try to launch it says: 

`➜  ~ wal -t -i /home/yolan/Pictures/Wallpapers/Final/
Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==0.5.6', 'console_scripts', 'wal')()
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 126, in main
    process_args(args)
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 100, in process_args
    image_file = image.get(args.i)
  File "/usr/lib/python3.6/site-packages/pywal/image.py", line 37, in get
    wal_img = get_random_image(image)
  File "/usr/lib/python3.6/site-packages/pywal/image.py", line 16, in get_random_image
    current_wall = os.path.basename(current_wall)
  File "/usr/lib/python3.6/posixpath.py", line 144, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
`

Also, I can't install it using AUR because it says 

`:: Installing python-pywal package(s)...
:: python-pywal package(s) failed to install.
:: ensure package version does not mismatch between .SRCINFO and PKGBUILD
:: ensure package name has a VCS suffix if this is a devel package
`
Just to let you know. 
Thanks !

**Comment by dylanaraps** [comment]
I can reproduce this, thanks!

**Comment by dylanaraps** [comment]
Fixed, I'll push a new version in a sec.

**Comment by dylanaraps** [comment]
I've pushed version `0.5.7` with the fix.

I'll also fix the aur package, thanks for informing me about it. :+1:

**Comment by Y0lan** [comment]
@dylanaraps the AUR package have not been fixed yet, or if yes, still the same error. 
You are welcome, this soft is the foundation of my entire rice, after it broke after update, all I had was green wallpaper, no polybar, etc. ^^ 
Thanks for your work, very appreciated ! 

-someone who lives in Africa

**Comment by dylanaraps** [comment]
I've contacted the maintainer of the AUR package and I'm waiting for his response. In the meantime here's a fixed PKGBUILD you can use.  (This will download the latest release)

Steps to use the snippet below:

1. `mkdir python-pywal`
2. `cd python-pywal`
3. Create a file called `PKGBUILD` and insert the code below.
4. `makepkg -si` 
5. Run `wal`

```sh
# Maintainer: Sean Haugh <seanphaugh@gmail.com>
pkgname=python-pywal
pkgver=0.5.7
pkgrel=2
pkgdesc="Generate and change colorschemes on the fly"
arch=('any')
url="https://github.com/dylanaraps/pywal/"
license=('MIT')
depends=(
  'python'
  'imagemagick'
)
optdepends=(
  'feh: set wallpaper'
  'nitrogen: set wallpaper'
)
provides=("python-pywal=${pkgver}-${pkgrel}")
source=("https://github.com/dylanaraps/${pkgname#python-}/archive/${pkgver}.tar.gz")
md5sums=('a2231b4f54595db4fa028f7fbccec987')

package() {
  cd "${srcdir}/${pkgname#python-}-${pkgver}"
  python setup.py install --prefix=/usr --root="${pkgdir}/" --optimize=1
  install -Dm644 "${srcdir}/${pkgname#python-}-${pkgver}/LICENSE.md" \
                 "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}

# vim:set ts=2 sw=2 et:
```

**Comment by Y0lan** [comment]
Oh, I thought YOU were the maintainer. 
Cheers !

**Comment by dylanaraps** [comment]
The aur package has been fixed. There are now two packages, `python-pywal` which follows each release and `python-pywal-git` which grabs the latest commit. :)
